hydra:
  searchpath:
    - file://${oc.env:PROJECT_ROOT}/src/configs
    - file://${oc.env:PROJECT_ROOT}/src/models/vp_sde/configs
  run:
    dir: /lustre/fsn1/projects/rech/krk/uqo89gi/projects/colab/lddm/${now:%Y-%m-%d_%H-%M-%S}/split_${split}/epoch_${epoch}/time_star_${predictor.predictor_config.time_star}/steps_${predictor.predictor_config.inference_steps}

defaults:
  - predictor: predictor_cvae_ldm3d
  - tester: default
  - data: adni_pet_cdl_3D
  - metrics: colab # add more metrics
  - dataloader: clinicadl
  - wrapper: clinicadl
  - saver: save_adni_pet
  - _self_

wrapper:
  seg_key: binary_hypo_mask
  mask_key: mni_icbm152_t1_tal_nlin_sym_09c_mask_cropped
  seg_threshold: 0.90
  mode_threshold: greater
  original_image_key: original_image


dataloader:
  test_loader:
    batch_size: 5
    prefetch_factor: 2
    num_workers: 5

predictor:
  predictor_config:
    time_star: 0.7
    inference_steps: 100

device: cuda
split: 0

diffusion_model_cfg: /lustre/fswork/projects/rech/uwe/ute94bq/shared_dir/models/journal/latent_ddpm/vqvae_spatial/${split}/.hydra/config.yaml
diffusion_model_ckpt: /lustre/fswork/projects/rech/uwe/ute94bq/shared_dir/models/journal/latent_ddpm/vqvae_spatial/${split}/best_loss/best.pt

vae_model_cfg: /lustre/fswork/projects/rech/uwe/ute94bq/shared_dir/models/journal/vqvae_spatial/vqvae_spatial_config.yaml
vae_model_ckpt: /lustre/fswork/projects/rech/uwe/ute94bq/shared_dir/models/journal/vqvae_spatial/${split}/VQVAE_training_2026-03-25_19-55-03/final_model/model.pt
